name: Create Pull Request

on:
  push:
    branches:
      - ideas

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Create Pull Request
      run: |
        git checkout master
        git merge origin/ideas --no-commit --no-ff
        git commit -am "Merge ideas into master"
        git push origin master
